apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{.Values.namespace}}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;
    
    worker_processes auto;
    
    events {
        worker_connections 1024;
    }
    
    http {
      log_format compression '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" "$gzip_ratio"';
      server {
        listen 8080;
        root /var/www/jackbourner.co.uk;
        location / {
          proxy_pass http://127.0.0.1:8000/;
          proxy_set_header    Host $host;
          proxy_set_header    X-Forwarded-Proto $scheme;
        }
        location /static/myapp {
          autoindex on;
          alias /var/www/jackbourner.co.uk/static/myapp/;
        }
      }
    }